name: Re-Tag and Push Latest Image to Docker Hub When PR is Merged

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  update-latest-tag:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      # Checkout the merged PR code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extract the GitHead Tag (Short SHA)
      - name: Get commit SHA
        id: get_sha
        run: echo "sha_short=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-7)" >> $GITHUB_ENV

      # Pull, Tag, and Push the Image with 'latest' Tag
      - name: Tag and Push Latest
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/mern-server:${{ env.sha_short }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/mern-server:${{ env.sha_short }} ${{ secrets.DOCKER_USERNAME }}/mern-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-server:latest
