name: Jenkins CI PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the pull request branch
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extract the commit SHA
      - name: Get commit SHA
        id: get_sha
        run: echo "sha_short=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-7)" >> $GITHUB_ENV

      # Build and tag the Docker image
      - name: Build Docker image
        run: |
          docker build \
            --tag ${{ secrets.DOCKER_USERNAME }}/mern-server:${{ env.sha_short }} \
            ./server

      # Push the Docker image with both tags
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-server:${{ env.sha_short }}

      - name: Trigger Jenkins Job
        id: trigger
        run: |
          # Define variables
          JOB_NAME="ASM2-Pipeline"
          JENKINS_URL="${{ secrets.JENKINS_URL }}"
          USER="${{ secrets.JENKINS_USER }}"
          API_TOKEN="${{ secrets.JENKINS_API_TOKEN }}"
          echo "Image Tag: ${{ secrets.DOCKER_USERNAME }}/mern-server:${{ env.sha_short }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"

          # Get Jenkins Crumb
          CRUMB=$(curl -s --user "${USER}:${API_TOKEN}" "${JENKINS_URL}/crumbIssuer/api/json" | jq -r '.crumb')

          # Trigger Jenkins job and get queue URL
          curl -s -X POST "${JENKINS_URL}/job/${JOB_NAME}/build" \
            --user "${USER}:${API_TOKEN}" \
            -H "Jenkins-Crumb:${CRUMB}" \
            --data-urlencode "image_tag=${{ secrets.DOCKER_USERNAME }}/mern-server:${{ env.sha_short }}"

      # Step 5: Wait for Jenkins Job to Complete
      - name: Wait for Jenkins Job
        id: wait_jenkins
        run: |
          JOB_NAME="ASM2-Pipeline"
          JENKINS_URL="${{ secrets.JENKINS_URL }}"
          USER="${{ secrets.JENKINS_USER }}"
          API_TOKEN="${{ secrets.JENKINS_API_TOKEN }}"
          BUILD_URL="$JENKINS_URL/job/$JOB_NAME/lastBuild/api/json"
          STATUS="IN_PROGRESS"

          while [ "$STATUS" != "SUCCESS" ] && [ "$STATUS" != "FAILURE" ]; do
            echo "Checking Jenkins job status..."
            sleep 10
            STATUS=$(curl -s --user $USER:$API_TOKEN $BUILD_URL | jq -r '.result')
            echo "Current status: $STATUS"
          done

          if [ "$STATUS" == "SUCCESS" ]; then
            echo "Jenkins job completed successfully!"
          else
            echo "Jenkins job failed. Exiting with error."
            exit 1
          fi

       # Trigger docker-final-ci Workflow
      - name: Trigger Docker CI Final
        if: ${{ steps.wait_jenkins.outcome == 'SUCCESS' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-docker-final-ci
          client-payload: |
            {
              "image_tag": "${{ secrets.DOCKER_USERNAME }}/mern-server:${{ env.sha_short }}"
            }