name: Jenkins CI PR

on:
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the pull request branch
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extract the commit SHA
      - name: Get commit SHA
        id: get_sha
        run: echo "sha_short=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-7)" >> $GITHUB_ENV

      # Build and tag the Docker image
      - name: Build Docker image
        run: |
          docker build \
            --tag ${{ secrets.DOCKER_USERNAME }}/mern-server:${{ env.sha_short }} \
            ./server

      # Push the Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-server:${{ env.sha_short }}

      - name: Trigger Jenkins Job
        id: trigger
        run: |
          # Define variables
          JOB_NAME="ASM2-Pipeline"
          JENKINS_URL="${{ secrets.JENKINS_URL }}"
          USER="${{ secrets.JENKINS_USER }}"
          API_TOKEN="${{ secrets.JENKINS_API_TOKEN }}"
          echo "Image Tag: ${{ secrets.DOCKER_USERNAME }}/mern-server:${{ env.sha_short }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"

          # Get Jenkins Crumb
          CRUMB=$(curl -s --user "${USER}:${API_TOKEN}" "${JENKINS_URL}/crumbIssuer/api/json" | jq -r '.crumb')

          # Trigger Jenkins job and get queue URL
          # curl -s -X POST "${JENKINS_URL}/job/${JOB_NAME}/buildWithParameters" \
          #   --user "${USER}:${API_TOKEN}" \
          #   -H "Jenkins-Crumb:${CRUMB}" \
          #   --data-urlencode "image_tag=${{ secrets.DOCKER_USERNAME }}/mern-server:${{ env.sha_short }}"

          # Trigger Jenkins job and get HTTP response code
          HTTP_RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" -X POST "${JENKINS_URL}/job/${JOB_NAME}/buildWithParameters" \
            --user "${USER}:${API_TOKEN}" \
            -H "Jenkins-Crumb:${CRUMB}" \
            --data-urlencode "image_tag=${{ secrets.DOCKER_USERNAME }}/mern-server:${{ env.sha_short }}"

          # Check if the response is in the 400-405 range
          if [[ "$HTTP_RESPONSE" -ge 400 && "$HTTP_RESPONSE" -le 405 ]]; then
            echo "Failed to trigger Jenkins job. HTTP response code: $HTTP_RESPONSE"
            exit 1
          fi  
          
          echo "Successfully triggered Jenkins job. HTTP response code: $HTTP_RESPONSE"

      # Wait for Jenkins Job to Complete and Show Logs
      - name: Wait for Jenkins Job
        id: wait_jenkins
        run: |
          JOB_NAME="ASM2-Pipeline"
          JENKINS_URL="${{ secrets.JENKINS_URL }}"
          USER="${{ secrets.JENKINS_USER }}"
          API_TOKEN="${{ secrets.JENKINS_API_TOKEN }}"
          BUILD_URL="$JENKINS_URL/job/$JOB_NAME/lastBuild/api/json"
          CONSOLE_OUTPUT_URL="$JENKINS_URL/job/$JOB_NAME/lastBuild/consoleText"
          STATUS="IN_PROGRESS"

          while [ "$STATUS" != "SUCCESS" ] && [ "$STATUS" != "FAILURE" ]; do
            echo "Checking Jenkins job status..."
            sleep 10
            STATUS=$(curl -s --user $USER:$API_TOKEN $BUILD_URL | jq -r '.result')
            echo "Current status: $STATUS"
          done

          if [ "$STATUS" == "SUCCESS" ]; then
            echo "Jenkins job completed successfully!"
            echo "Fetching Jenkins console output for details..."
            curl -s --user $USER:$API_TOKEN $CONSOLE_OUTPUT_URL
          else
            echo "Jenkins job failed. Fetching Jenkins console output for error details..."
            curl -s --user $USER:$API_TOKEN $CONSOLE_OUTPUT_URL
            exit 1
          fi

      # Tag and push the latest Docker image
      - name: Tag and Push Latest
        if: ${{ steps.wait_jenkins.outcome == 'SUCCESS' }}
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/mern-server:${{ env.sha_short }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/mern-server:${{ env.sha_short }} ${{ secrets.DOCKER_USERNAME }}/mern-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-server:latest