name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17' # Update this to match your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run ESLint and Check for Syntax Errors
        id: run-eslint
        run: |
          npx eslint . -f json -o eslint-report.json
        continue-on-error: false # Fail the workflow if ESLint exits with a non-zero code

      - name: Run reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          level: error
          eslint_input: eslint-report.json
          fail_on_error: true # Fail if errors are reported
          filter_mode: added
          reviewdog_flags: '-filter-mode=nofilter'
