name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review # Posts ESLint issues as comments on the PR
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint_flags: '.' # Specify files or directories for ESLint
          fail_level: warning # Ensure workflow does not fail, post as comments