name: Jenkins CI PR

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job
        id: trigger
        run: |
          # Define variables
          JOB_NAME="ASM2-Pipeline"
          JENKINS_URL="${{ secrets.JENKINS_URL }}"
          USER="${{ secrets.JENKINS_USER }}"
          API_TOKEN="${{ secrets.JENKINS_API_TOKEN }}"
          echo "Image Tag: ${{ secrets.DOCKER_USERNAME }}/mern-server:latest"
          echo "PR Number: ${{ github.event.pull_request.number }}"

          # Get Jenkins Crumb
          CRUMB=$(curl -s --user "${USER}:${API_TOKEN}" "${JENKINS_URL}/crumbIssuer/api/json" | jq -r '.crumb')

          # Trigger Jenkins job 
          curl -s -X POST "${JENKINS_URL}/job/${JOB_NAME}/build" \
            --user "${USER}:${API_TOKEN}" \
            -H "Jenkins-Crumb:${CRUMB}" \
            --data-urlencode "image_tag=${{ secrets.DOCKER_USERNAME }}/mern-server:latest"

      # Step 5: Wait for Jenkins Job to Complete
      - name: Wait for Jenkins Job
        id: wait_jenkins
        run: |
          JOB_NAME="ASM2-Pipeline"
          JENKINS_URL="${{ secrets.JENKINS_URL }}"
          USER="${{ secrets.JENKINS_USER }}"
          API_TOKEN="${{ secrets.JENKINS_API_TOKEN }}"
          BUILD_URL="$JENKINS_URL/job/$JOB_NAME/lastBuild/api/json"
          STATUS="IN_PROGRESS"

          while [ "$STATUS" != "SUCCESS" ] && [ "$STATUS" != "FAILURE" ]; do
            echo "Checking Jenkins job status..."
            sleep 10
            STATUS=$(curl -s --user $USER:$API_TOKEN $BUILD_URL | jq -r '.result')
            echo "Current status: $STATUS"
          done

          if [ "$STATUS" == "SUCCESS" ]; then
            echo "Jenkins job completed successfully!"
          else
            echo "Jenkins job failed. Exiting with error."
            exit 1
          fi